### ISSUE TITLE
how to setup

### ISSUE THREAD

**Issue by atcasanova** [shizunge/blocky-postgresql#2]
i'm currently using my blocky  in docker using this docker-compose file. Can you help me adapt it to use postgre and your dashboard?

```yml
version: "3"

services:
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./blocky/config.yml:/app/config.yml
      - queryLogs:/logs
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    restart: always

volumes:
    prometheus_data: {}
    grafana_data: {}
    queryLogs: {}
```

**Comment by shizunge** [comment]
add a service to docker compose. make sure blocky, postgres in the same network for write and postgres and grafana in the same network for read, or simple put all three in the same network.
```
  blocky_db:
    image: postgres:14
    networks:
      - blocky
      - postgres
      - grafana
    environment:
      - POSTGRES_USER=blocky
      - POSTGRES_PASSWORD=blocky
      - POSTGRES_DB=blocky
    volumes:
      - blocky-db:/var/lib/postgresql/data
```

update blocky config
```
# optional: write query information (question, answer, client, duration etc.) to daily csv file
queryLog:
  # optional one of: mysql, postgresql, csv, csv-client. If empty, log to console
  type: postgresql
  # directory (should be mounted as volume in docker) for csv, db connection string for mysql/postgresql
  # target: db_user:db_password@tcp(db_host_or_ip:3306)/db_name?charset=utf8mb4&parseTime=True&loc=Local
  #postgresql target: postgres://user:password@db_host_or_ip:5432/db_name
  target: postgres://blocky:blocky@blocky_db:5432/blocky
  # if > 0, deletes log files which are older than ... days
  logRetentionDays: 45
  # optional: Max attempts to create specific query log writer, default: 3
  creationAttempts: 60
  # optional: Time between the creation attempts, default: 2s
  creationCooldown: 5s
```

**Comment by atcasanova** [comment]
So, i've update my docker-compose file as you suggested:

```yml
version: "3"

services:
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./blocky/config.yml:/app/config.yml
      - queryLogs:/logs
  blocky_db:
    image: postgres:14
    environment:
      - POSTGRES_USER=blocky
      - POSTGRES_PASSWORD=blocky
      - POSTGRES_DB=blocky
    volumes:
      - blocky-db:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    restart: always

volumes:
    prometheus_data: {}
    grafana_data: {}
    queryLogs: {}
    blocky-db: {}
```

and tried to import your dashboard, but it says there are no sources os type postgresql:

![image](https://github.com/shizunge/blocky-postgresql-dashboard/assets/2973929/d7c14ccb-99e0-48ec-a29b-a1d49b50dbdc)

besides that, i noticed that the blocky-db container started with another name (that i later used to update the docker-compose file):

```
CONTAINER ID   IMAGE                    COMMAND                  CREATED         STATUS                   PORTS                                                               NAMES
510ead771c1f   grafana/grafana          "/run.sh"                3 minutes ago   Up 3 minutes             0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                               grafana
eb778f0f0cf1   postgres:14              "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes             5432/tcp                                                               blocky-blocky_db-1
6832b11c9805   spx01/blocky             "/app/blocky"            3 minutes ago   Up 3 minutes (healthy)   0.0.0.0:53->53/tcp, :::53->53/tcp, 0.0.0.0:4000->4000/tcp, 0.0.0.0:53->53/udp, :::4000->4000/tcp, :::53->53/udp   blocky
1858d4f82709   prom/prometheus          "/bin/prometheus --c…"   3 minutes ago   Up 3 minutes             0.0.0.0:9090->9090/tcp, :::9090->9090/tcp                                                               prometheus
```

but still got the same error.

Thanks for your help
