### ISSUE TITLE
Request: Could you publish instructions to install this on a Debian machine?

### ISSUE THREAD

**Issue by gspannu** [shizunge/blocky-postgresql#4]
Could you please publish instructions to have this Grafana Dashboard on a Debian machine (instead of a docker container)?

I already have blocky running on an Alpine Linux machine. Super small footprint.
I already have Grafana running on another Debian machine. 
I wish to install Postgres on tis Debian machine (same as Grafana) and have this dashboard working.

**Could you please post instructions for Postgres installation, changes to blocky yaml file, etc and any other bits needed?**

Your dashboard is quite cool and looks a lot better than the default (in Grafana Labs).... so very keen to use this.
Thanks.

**Comment by shizunge** [comment]
I will add the following information to readme later.

Links:
Install postgresql: https://www.postgresql.org/docs/current/tutorial-install.html
Install Grafana: https://grafana.com/docs/grafana/latest/setup-grafana/installation/

Example blokcy setup, the `queryLog` section.
https://0xerr0r.github.io/blocky/v0.23/configuration/#query-logging
```
# optional: write query information (question, answer, client, duration etc.) to daily csv file
queryLog:
  # optional one of: mysql, postgresql, csv, csv-client. If empty, log to console
  type: postgresql
  # directory (should be mounted as volume in docker) for csv, db connection string for mysql/postgresql
  # postgresql target: postgres://user:password@db_host_or_ip:5432/db_name
  target: postgres://blocky_writer:blocky_password@blocky_db.blocky_network:5432/blocky_db
```
